site_name: 'Contact Tools — Drupal module'
pages:
  - 'Home': index.md
  - 'Installation': installation.md
  - 'Service': service.md
  - 'Twig': twig.md
  - 'Filter': filter.md
  - 'Hooks': hooks.md
  - 'Examples': examples.md
